### ISSUE TITLE
Enable events-incremental and committees scrapers for Toronto

### ISSUE THREAD

**Issue by patcon** [opennorth/scrapers_ca_app#11]
Is this an easy thing to add?

**Comment by jpmckinney** [comment]
What do the commands look like when run individually locally?

**Comment by patcon** [comment]
if I understand you correctly:

    pupa update ca_on_toronto events-incremental committees people

**Comment by jpmckinney** [comment]
I've added them individually. Let me know if any scrapers are interdependent.

**Comment by patcon** [comment]
Assuming the scrape doesn't have anything to do with what's already in the DB (which I think is the case), then they should be fine. Just won't resolve participants/related_entities/etc.

**Comment by patcon** [comment]
And thanks!
